//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ylesanne3.OISTeenus {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tund", Namespace="http://idu0075.ttu.ee/iabb111881/ois/teenus")]
    [System.SerializableAttribute()]
    public partial class Tund : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AineNimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ÕppejõuNimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuumiNrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AineNimi {
            get {
                return this.AineNimiField;
            }
            set {
                if ((object.ReferenceEquals(this.AineNimiField, value) != true)) {
                    this.AineNimiField = value;
                    this.RaisePropertyChanged("AineNimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ÕppejõuNimi {
            get {
                return this.ÕppejõuNimiField;
            }
            set {
                if ((object.ReferenceEquals(this.ÕppejõuNimiField, value) != true)) {
                    this.ÕppejõuNimiField = value;
                    this.RaisePropertyChanged("ÕppejõuNimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RuumiNr {
            get {
                return this.RuumiNrField;
            }
            set {
                if ((object.ReferenceEquals(this.RuumiNrField, value) != true)) {
                    this.RuumiNrField = value;
                    this.RaisePropertyChanged("RuumiNr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://idu0075.ttu.ee/iabb111881/ois/teenus", ConfigurationName="OISTeenus.TeenusSoap")]
    public interface TeenusSoap {
        
        // CODEGEN: Generating message contract since element name nimi from namespace http://idu0075.ttu.ee/iabb111881/ois/teenus is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://idu0075.ttu.ee/iabb111881/ois/teenus/GetTunniplaan", ReplyAction="*")]
        Ylesanne3.OISTeenus.GetTunniplaanResponse GetTunniplaan(Ylesanne3.OISTeenus.GetTunniplaanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://idu0075.ttu.ee/iabb111881/ois/teenus/GetTunniplaan", ReplyAction="*")]
        System.Threading.Tasks.Task<Ylesanne3.OISTeenus.GetTunniplaanResponse> GetTunniplaanAsync(Ylesanne3.OISTeenus.GetTunniplaanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTunniplaanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTunniplaan", Namespace="http://idu0075.ttu.ee/iabb111881/ois/teenus", Order=0)]
        public Ylesanne3.OISTeenus.GetTunniplaanRequestBody Body;
        
        public GetTunniplaanRequest() {
        }
        
        public GetTunniplaanRequest(Ylesanne3.OISTeenus.GetTunniplaanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://idu0075.ttu.ee/iabb111881/ois/teenus")]
    public partial class GetTunniplaanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nimi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string matrikliNr;
        
        public GetTunniplaanRequestBody() {
        }
        
        public GetTunniplaanRequestBody(string nimi, string matrikliNr) {
            this.nimi = nimi;
            this.matrikliNr = matrikliNr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTunniplaanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTunniplaanResponse", Namespace="http://idu0075.ttu.ee/iabb111881/ois/teenus", Order=0)]
        public Ylesanne3.OISTeenus.GetTunniplaanResponseBody Body;
        
        public GetTunniplaanResponse() {
        }
        
        public GetTunniplaanResponse(Ylesanne3.OISTeenus.GetTunniplaanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://idu0075.ttu.ee/iabb111881/ois/teenus")]
    public partial class GetTunniplaanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ylesanne3.OISTeenus.Tund[] GetTunniplaanResult;
        
        public GetTunniplaanResponseBody() {
        }
        
        public GetTunniplaanResponseBody(Ylesanne3.OISTeenus.Tund[] GetTunniplaanResult) {
            this.GetTunniplaanResult = GetTunniplaanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TeenusSoapChannel : Ylesanne3.OISTeenus.TeenusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeenusSoapClient : System.ServiceModel.ClientBase<Ylesanne3.OISTeenus.TeenusSoap>, Ylesanne3.OISTeenus.TeenusSoap {
        
        public TeenusSoapClient() {
        }
        
        public TeenusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeenusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeenusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeenusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ylesanne3.OISTeenus.GetTunniplaanResponse Ylesanne3.OISTeenus.TeenusSoap.GetTunniplaan(Ylesanne3.OISTeenus.GetTunniplaanRequest request) {
            return base.Channel.GetTunniplaan(request);
        }
        
        public Ylesanne3.OISTeenus.Tund[] GetTunniplaan(string nimi, string matrikliNr) {
            Ylesanne3.OISTeenus.GetTunniplaanRequest inValue = new Ylesanne3.OISTeenus.GetTunniplaanRequest();
            inValue.Body = new Ylesanne3.OISTeenus.GetTunniplaanRequestBody();
            inValue.Body.nimi = nimi;
            inValue.Body.matrikliNr = matrikliNr;
            Ylesanne3.OISTeenus.GetTunniplaanResponse retVal = ((Ylesanne3.OISTeenus.TeenusSoap)(this)).GetTunniplaan(inValue);
            return retVal.Body.GetTunniplaanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ylesanne3.OISTeenus.GetTunniplaanResponse> Ylesanne3.OISTeenus.TeenusSoap.GetTunniplaanAsync(Ylesanne3.OISTeenus.GetTunniplaanRequest request) {
            return base.Channel.GetTunniplaanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ylesanne3.OISTeenus.GetTunniplaanResponse> GetTunniplaanAsync(string nimi, string matrikliNr) {
            Ylesanne3.OISTeenus.GetTunniplaanRequest inValue = new Ylesanne3.OISTeenus.GetTunniplaanRequest();
            inValue.Body = new Ylesanne3.OISTeenus.GetTunniplaanRequestBody();
            inValue.Body.nimi = nimi;
            inValue.Body.matrikliNr = matrikliNr;
            return ((Ylesanne3.OISTeenus.TeenusSoap)(this)).GetTunniplaanAsync(inValue);
        }
    }
}
