//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace News.FormApp.Services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewsServiceSoap", Namespace="http://idu0075.ttu.ee/111881/News/")]
    public partial class NewsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AnalyzeOperationCompleted;
        
        /// <remarks/>
        public NewsService() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["news"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost:40002/NewsService.asmx";
            }
        }
        
        /// <remarks/>
        public event AnalyzeCompletedEventHandler AnalyzeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idu0075.ttu.ee/111881/News/Analyze", RequestNamespace="http://idu0075.ttu.ee/111881/News/", ResponseNamespace="http://idu0075.ttu.ee/111881/News/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AnalyzeResult[] Analyze(string url, System.DateTime time) {
            object[] results = this.Invoke("Analyze", new object[] {
                        url,
                        time});
            return ((AnalyzeResult[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAnalyze(string url, System.DateTime time, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Analyze", new object[] {
                        url,
                        time}, callback, asyncState);
        }
        
        /// <remarks/>
        public AnalyzeResult[] EndAnalyze(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AnalyzeResult[])(results[0]));
        }
        
        /// <remarks/>
        public void AnalyzeAsync(string url, System.DateTime time) {
            this.AnalyzeAsync(url, time, null);
        }
        
        /// <remarks/>
        public void AnalyzeAsync(string url, System.DateTime time, object userState) {
            if ((this.AnalyzeOperationCompleted == null)) {
                this.AnalyzeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnalyzeOperationCompleted);
            }
            this.InvokeAsync("Analyze", new object[] {
                        url,
                        time}, this.AnalyzeOperationCompleted, userState);
        }
        
        private void OnAnalyzeOperationCompleted(object arg) {
            if ((this.AnalyzeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnalyzeCompleted(this, new AnalyzeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://idu0075.ttu.ee/111881/News/")]
    public partial class AnalyzeResult {
        
        private string stockTickerField;
        
        private string newsUrlField;
        
        private System.DateTime newsDateField;
        
        private double openPriceField;
        
        private double closePriceField;
        
        /// <remarks/>
        public string StockTicker {
            get {
                return this.stockTickerField;
            }
            set {
                this.stockTickerField = value;
            }
        }
        
        /// <remarks/>
        public string NewsUrl {
            get {
                return this.newsUrlField;
            }
            set {
                this.newsUrlField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NewsDate {
            get {
                return this.newsDateField;
            }
            set {
                this.newsDateField = value;
            }
        }
        
        /// <remarks/>
        public double OpenPrice {
            get {
                return this.openPriceField;
            }
            set {
                this.openPriceField = value;
            }
        }
        
        /// <remarks/>
        public double ClosePrice {
            get {
                return this.closePriceField;
            }
            set {
                this.closePriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void AnalyzeCompletedEventHandler(object sender, AnalyzeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnalyzeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnalyzeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnalyzeResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnalyzeResult[])(this.results[0]));
            }
        }
    }
}
