//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace NewsWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://idu0075.ttu.ee/111881/Stocks/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTickersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPricesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWeeklyPriceOperationCompleted;
        
        /// <remarks/>
        public Service() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["stocks"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost:40001/Service.asmx";
            }
        }
        
        /// <remarks/>
        public event GetTickersCompletedEventHandler GetTickersCompleted;
        
        /// <remarks/>
        public event GetPricesCompletedEventHandler GetPricesCompleted;
        
        /// <remarks/>
        public event GetWeeklyPriceCompletedEventHandler GetWeeklyPriceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idu0075.ttu.ee/111881/Stocks/GetTickers", RequestNamespace="http://idu0075.ttu.ee/111881/Stocks/", ResponseNamespace="http://idu0075.ttu.ee/111881/Stocks/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetTickers() {
            object[] results = this.Invoke("GetTickers", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTickers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTickers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetTickers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTickersAsync() {
            this.GetTickersAsync(null);
        }
        
        /// <remarks/>
        public void GetTickersAsync(object userState) {
            if ((this.GetTickersOperationCompleted == null)) {
                this.GetTickersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTickersOperationCompleted);
            }
            this.InvokeAsync("GetTickers", new object[0], this.GetTickersOperationCompleted, userState);
        }
        
        private void OnGetTickersOperationCompleted(object arg) {
            if ((this.GetTickersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTickersCompleted(this, new GetTickersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idu0075.ttu.ee/111881/Stocks/GetPrices", RequestNamespace="http://idu0075.ttu.ee/111881/Stocks/", ResponseNamespace="http://idu0075.ttu.ee/111881/Stocks/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockPrice[] GetPrices(string ticker, System.DateTime from, System.DateTime to) {
            object[] results = this.Invoke("GetPrices", new object[] {
                        ticker,
                        from,
                        to});
            return ((StockPrice[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPrices(string ticker, System.DateTime from, System.DateTime to, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPrices", new object[] {
                        ticker,
                        from,
                        to}, callback, asyncState);
        }
        
        /// <remarks/>
        public StockPrice[] EndGetPrices(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StockPrice[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPricesAsync(string ticker, System.DateTime from, System.DateTime to) {
            this.GetPricesAsync(ticker, from, to, null);
        }
        
        /// <remarks/>
        public void GetPricesAsync(string ticker, System.DateTime from, System.DateTime to, object userState) {
            if ((this.GetPricesOperationCompleted == null)) {
                this.GetPricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPricesOperationCompleted);
            }
            this.InvokeAsync("GetPrices", new object[] {
                        ticker,
                        from,
                        to}, this.GetPricesOperationCompleted, userState);
        }
        
        private void OnGetPricesOperationCompleted(object arg) {
            if ((this.GetPricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPricesCompleted(this, new GetPricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://idu0075.ttu.ee/111881/Stocks/GetWeeklyPrice", RequestNamespace="http://idu0075.ttu.ee/111881/Stocks/", ResponseNamespace="http://idu0075.ttu.ee/111881/Stocks/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockWeekPrice GetWeeklyPrice(string stock, System.DateTime date) {
            object[] results = this.Invoke("GetWeeklyPrice", new object[] {
                        stock,
                        date});
            return ((StockWeekPrice)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWeeklyPrice(string stock, System.DateTime date, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWeeklyPrice", new object[] {
                        stock,
                        date}, callback, asyncState);
        }
        
        /// <remarks/>
        public StockWeekPrice EndGetWeeklyPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StockWeekPrice)(results[0]));
        }
        
        /// <remarks/>
        public void GetWeeklyPriceAsync(string stock, System.DateTime date) {
            this.GetWeeklyPriceAsync(stock, date, null);
        }
        
        /// <remarks/>
        public void GetWeeklyPriceAsync(string stock, System.DateTime date, object userState) {
            if ((this.GetWeeklyPriceOperationCompleted == null)) {
                this.GetWeeklyPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWeeklyPriceOperationCompleted);
            }
            this.InvokeAsync("GetWeeklyPrice", new object[] {
                        stock,
                        date}, this.GetWeeklyPriceOperationCompleted, userState);
        }
        
        private void OnGetWeeklyPriceOperationCompleted(object arg) {
            if ((this.GetWeeklyPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWeeklyPriceCompleted(this, new GetWeeklyPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://idu0075.ttu.ee/111881/Stocks/")]
    public partial class StockPrice {
        
        private System.DateTime dateField;
        
        private double openPriceField;
        
        private double highPriceField;
        
        private double lowPriceField;
        
        private double closePriceField;
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public double OpenPrice {
            get {
                return this.openPriceField;
            }
            set {
                this.openPriceField = value;
            }
        }
        
        /// <remarks/>
        public double HighPrice {
            get {
                return this.highPriceField;
            }
            set {
                this.highPriceField = value;
            }
        }
        
        /// <remarks/>
        public double LowPrice {
            get {
                return this.lowPriceField;
            }
            set {
                this.lowPriceField = value;
            }
        }
        
        /// <remarks/>
        public double ClosePrice {
            get {
                return this.closePriceField;
            }
            set {
                this.closePriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://idu0075.ttu.ee/111881/Stocks/")]
    public partial class StockWeekPrice {
        
        private int yearField;
        
        private int weekField;
        
        private double startPriceField;
        
        private double endPriceField;
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public int Week {
            get {
                return this.weekField;
            }
            set {
                this.weekField = value;
            }
        }
        
        /// <remarks/>
        public double StartPrice {
            get {
                return this.startPriceField;
            }
            set {
                this.startPriceField = value;
            }
        }
        
        /// <remarks/>
        public double EndPrice {
            get {
                return this.endPriceField;
            }
            set {
                this.endPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetTickersCompletedEventHandler(object sender, GetTickersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTickersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTickersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetPricesCompletedEventHandler(object sender, GetPricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockPrice[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockPrice[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetWeeklyPriceCompletedEventHandler(object sender, GetWeeklyPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWeeklyPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWeeklyPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockWeekPrice Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockWeekPrice)(this.results[0]));
            }
        }
    }
}
